# Generated by Django 3.2.8 on 2021-11-01 07:34

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='api',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('isbn', models.CharField(max_length=100)),
                ('authors', models.CharField(max_length=1000)),
                ('number_of_pages', models.IntegerField(max_length=10)),
                ('publisher', models.CharField(max_length=100)),
                ('country', models.CharField(max_length=100)),
                ('release_date', models.DateTimeField()),
            ],
        ),
    ]
