# Generated by Django 3.2.8 on 2021-11-01 07:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='api',
            name='number_of_pages',
            field=models.IntegerField(),
        ),
    ]
