# Generated by Django 3.2.8 on 2021-11-01 07:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_alter_api_number_of_pages'),
    ]

    operations = [
        migrations.AlterField(
            model_name='api',
            name='release_date',
            field=models.DateField(),
        ),
    ]
