# Generated by Django 3.2.8 on 2021-11-01 11:58

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_alter_api_release_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='api',
            name='authors',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=100), size=None),
        ),
    ]
